# Find the nasm assembler

SET(ASM_DIALECT "-NASM")

SET(CMAKE_ASM${ASM_DIALECT}_COMPILER_INIT nasm)

IF(NOT CMAKE_ASM${ASM_DIALECT}_COMPILER)
  IF(WIN32)
    FIND_PROGRAM(CMAKE_ASM${ASM_DIALECT}_COMPILER nasmw)
  ELSE(WIN32)
    FIND_PROGRAM(CMAKE_ASM${ASM_DIALECT}_COMPILER nasm)
  ENDIF(WIN32)
ENDIF(NOT CMAKE_ASM${ASM_DIALECT}_COMPILER)

INCLUDE(CMakeDetermineASMCompiler)
SET(ASM_DIALECT)



