.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LIGHTSPARK 1 "June 28, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
lightspark \- a free Flash player
.SH SYNOPSIS
.B lightspark
.RI [ options ] " file.swf" ...
.SH DESCRIPTION
This manual page documents briefly the
.B lightspark
standalone player.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBlightspark\fP is a modern Adobe Flash player.
It is currently in a very experimantal phase. This is the standalone player.
.PP
You might wish to see the project website at http://lightspark.sf.net or our 
technical blog at http://allievi.sssup.it/techblog
.SH AUTHOR
lightspark was written by Alessandro Pignotti.
.PP
This manual page was written by Jacopo Corbetta <j.corbetta@sssup.it>,
for the Debian project (and may be used by others).
