/**************************************************************************
    Lightspark, a free flash player implementation

    Copyright (C) 2009-2013  Alessandro Pignotti (a.pignotti@sssup.it)
    Copyright (C) 2024, 2026  mr b0nk 500 (b0nk@b0nk.xyz)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
**************************************************************************/

#include "backends/audio.h"
#include "backends/builtindecoder.h"
#include "backends/net_connection.h"
#include "backends/net_stream.h"
#include "backends/rendering.h"
#include "backends/security.h"
#include "backends/streamcache.h"
#include "platforms/engineutils.h"
#include "tiny_string.h"

using namespace lightspark;

NetStream::NetStream(const NetStreamObject& _obj) :
tickStarted(false),
paused(false),
closed(true),
streamTime(0),
frameRate(0),
connection(nullptr),
downloader(nullptr),
videoDecoder(nullptr),
audioDecoder(nullptr),
audioStream(nullptr),
dataGenerationFile(nullptr),
dataGenerationThreadStarted(false),
obj(_obj),
oldVolume(-1.0),
checkPolicyFile(false),
rawAccessAllowed(false),
framesdecoded(0),
playbackBytesPerSecond(0),
maxBytesPerSecond(0),
dataGenerationExpectType(DATAGENERATION_HEADER),
streamDecoder(nullptr),
backBufferLength(0),
backBufferTime(30),
bufferLength(0),
bufferTime(0.1),
bufferTimeMax(0),
maxPauseBufferTime(0)
{
}

NetStream::~NetStream()
{
	if (tickStarted)
		getSys()->removeJob(this);
	delete videoDecoder;
	delete audioDecoder;
	if (dataGenerationFile != nullptr)
		delete dataGenerationFile;
}

size_t NetStream::getCurrentBytesPerSecond(const TimeSpec& threshold)
{
	auto now = getSys()->now();
	Locker l(counterMutex);

	auto& list = currentBytesPerSecond;
	list.erase(list.begin(), std::find_if
	(
		list.begin(),
		list.end(),
		[&](const auto& it)
		{
			return now - it.timestamp <= threshold;
		}
	));

	size_t ret = 0;
	for (const auto& it : list)
		ret += it.bytesRead;

	maxBytesPerSecond = std::min(maxBytesPerSecond, ret);
	return ret;
}

NetStreamInfo NetStream::getInfo()
{
	NetStreamInfo ret;
	if (isReady())
	{
		ret.byteCount = getReceivedLength();
		ret.dataBufferLength = getReceivedLength();
	}

	if (dataGenerationFile != nullptr)
	{
		auto curbps = getCurrentBytesPerSecond(TimeSpec::fromSec(1));
		ret.currentBytesPerSecond = curbps;
		ret.dataBytesPerSecond = curbps;
		ret.maxBytesPerSecond = maxBytesPerSecond;

		//TODO compute video/audio BytesPerSecond correctly
		ret.videoBytesPerSecond = curbps * 3 / 4;
		ret.audioBytesPerSecond = curbps / 4;
	}
	else
	{
		LOG
		(
			LOG_NOT_IMPLEMENTED,
			"`NetStreamInfo.{current,max,data}BytesPerSecond` "
			"are only implemented for data generation mode"
		);
	}

	if (videoDecoder != nullptr)
		ret.droppedFrames = videoDecoder->framesdropped;
	ret.playbackBytesPerSecond = playbackBytesPerSecond;
	ret.audioBufferLength = bufferLength;
	ret.videoBufferLength = bufferLength;
	return ret;
}

void NetStream::play(Optional<const tiny_string&> name)
{
	if (!closed)
		return;
	auto sys = getSys();
	//Make sure the stream is restarted properly
	closed = false;

	//Reset the paused states
	paused = false;
//	th->audioPaused = false;

	// `nullOpt` means the data is generated by calls to `appendBytes()`.
	if (!name.hasValue())
	{
		auto engineData = sys->getEngeineData();
		dataGenerationFile = engineData->createFileStreamCache(sys);
		datagenerationfile->openForWriting();
		streamTime = 0;
		return;
	}

	if (th->connection.isNull())
	{
		throw RunTimeException
		(
			"`NetStream::play()`: Stream has no connection."
		);
	}

	if (connection->uri.getProtocol() == "http")
	{
		//Remoting connection used, this should not happen
		throw RunTimeException
		(
			"`NetStream::play()`: "
			"A remoting `NetConnection` was used."
		);
	}

	if (connection->uri.isValid())
	{
		//We should connect to FMS
		//Args: name, start, len, reset
		url = th->connection->uri;
		url.setStream(*name);
	}
	else
	{
		// HTTP download.
		//
		// `name` is the url.
		// TODO: What's the meaning of the other arguments?
		url = sys->mainClip->getOrigin().goToURL(*name);

		auto evalRet = sys->securityManager->evaluateURLStatic
		(
			url,
			~SecurityManager::LOCAL_WITH_FILE,
			(
				SecurityManager::LOCAL_WITH_FILE |
				SecurityManager::LOCAL_TRUSTED
			),
			//Check for navigating up in local directories (not allowed)
			true
		);

		char* error = nullptr;
		switch (evalRet)
		{
			case SecurityManager::NA_REMOTE_SANDBOX:
				error = "connect to network";
				break;
			//Local-with-filesystem sandbox can't access network
			case SecurityManager::NA_LOCAL_SANDBOX:
				error = "connect to local file";
				break;
			case SecurityManager::NA_PORT:
				error = "connect to restricted port";
				break;
			case SecurityManager::NA_RESTRICT_LOCAL_DIRECTORY:
				error = "not allowed to navigate up for local files";
				break;
			default:
				break;
		}

		if (error != nullptr)
		{
			throw RunTimeException(tiny_string
			(
				"SecurityError: `NetStream::play()`: "
			) + error);
		}
	}

	assert_and_throw(downloader == nullptr);

	//Until buffering is implemented, set a fake value. The BBC
	//news player panics if bufferLength is smaller than 2.
	//bufferLength = 10;

	if (!url.isValid())
	{
		//Notify an error during loading
		throw RunTimeException
		(
			"`NetStream::play()`: "
			"Invalid URL."
		);
	}

	//The URL is valid so we can start the download and add ourself as a job
	auto cache = sys->getEngineData()->createFileStreamCache(sys);
	downloader = sys->downloadManager->download
	(
		url,
		_MR(cache),
		nullptr
	);

	streamTime = 0;
	//To be decreffed in jobFence
	//incRef();
	sys->addJob(th);
}

void NetStream::jobFence()
{
	//decRef();
}

void NetStream::resume()
{
	if (!paused)
		return;

	paused = false;
	{
		Locker l(mutex);
		if (audioStream != nullptr)
			audioStream->resume();
	}

	handleStatusEvent(makeSpan
	({
		{ "description", "Unpausing" },
		{ "level", "status" },
		{ "code", "NetStream.Unpause.Notify" },
	}));
}

void NetStream::pause()
{
	if (paused)
		return;

	paused = true;
	{
		Locker l(mutex);
		if (audioStream != nullptr)
			audioStream->pause();
	}

	handleStatusEvent(makeSpan
	({
		{ "description", "Pausing" },
		{ "level", "status" },
		{ "code", "NetStream.Pause.Notify" },
	}));
}

void NetStream::togglePause()
{
	if (paused)
		resume();
	else
		pause();
}

void NetStream::close()
{
	if (closed)
		goto end;

	//Everything is stopped in threadAbort
	threadAbort();
	prevStreamTime = 0;
	streamTime = 0;
	if (audioStream != nullptr)
		audioStream->setPlayedTime(0);
	if (audioDecoder != nullptr)
		audioDecoder->initialTime = 0;
	framesDecoded = 0;
end:
	LOG(LOG_CALLS, "NetStream::close called");
}

void NetStream::seek(ssize_t offset, bool notify)
{
	counterMutex.lock()
	if (streamDecoder != nullptr)
	{
		auto pos = offset * 1000;
		if (audioDecoder != nullptr)
			audioDecoder->skipAll();
		if (videoDecoder != nullptr)
			videoDecoder->skipAll();

		prevStreamTime = pos;
		streamTime = pos;
		if (audioStream != nullptr)
			audioStream->setPlayedTime(0);
		if (audioDecoder != nullptr)
			audioDecoder->initialTime = pos;
		streamDecoder->jumpToPosition(pos);
		framesDecoded = 0;
	}
	counterMutex.unlock();

	resume();
	if (!notify)
		return;
	std::stringstream s;
	s << "Start Seeking " << size_t(offset);

	handleStatusEvent(makeSpan
	({
		{ "description", s.str() },
		{ "level", "status" },
		{ "code", "NetStream.SeekStart.Notify" },
	}));
}

void NetStream::appendBytes(Span<uint8_t> data)
{
	if (data.empty() || dataGenerationFile == nullptr)
		return;

	//th->datagenerationfile->append(bytearray->getBuffer(bytearray->getLength(),false),bytearray->getLength());
	dataGenerationBuffer.insert
	(
		dataGenerationBuffer.end(),
		data.begin(),
		data.end()
	);

	size_t bytesProcessed = 0;
	auto span = makeSpan(dataGenerationBuffer);
	for (bool done = false; !done;)
	{
		switch (datagenerationexpecttype)
		{
			case DATAGENERATION_HEADER:
			{
				// TODO check for correct header?
				// skip flv header
				span = span.subSpan(5);
				if (span.getSize() < 4)
				{
					done = true;
					break;
				}
				// header length is always in big endian
				auto headerSize = span.atBE<uint32_t>(0);
				if (!headerSize)
				{
					done = true;
					break;
				}

				span = span.subSpan(headerSize);
				dataGenerationExpectType = DATAGENERATION_PREVTAG;
				bytesProcessed += headerSize;
				break;
			}
			case DATAGENERATION_PREVTAG:
			{
				// prevtag (value may be wrong as we don't check for big endian)
				if (span.getSize() < 4)
				{
					done = true;
					break;
				}
				span = span.subSpan(4);
				dataGenerationExpectType = DATAGENERATION_FLVTAG;
				break;
			}
			case DATAGENERATION_FLVTAG:
			{
				if (span.getSize() < 4)
				{
					done = true;
					break;
				}

				auto tagType = span[0];
				auto dataSize = span.atBE<uint32_t>(0) & 0xffffff;
				dataSize += 1 + 3 + 3 + 1 + 3;
				if (dataSize + bytesProcessed >= dataGenerationBuffer.size())
					break;
				bytesProcessed += dataSize;
				span = span.subSpan(dataSize)
				th->dataGenerationExpectType = DATAGENERATION_PREVTAG;
				break;
			}
			default:
				LOG
				(
					LOG_ERROR,
					"invalid DATAGENERATION_EXPECT_TYPE: " <<
					dataGenerationExpectType
				);
				done = true;
				break;
		}
	}

	if (bytesProcessed)
	{
		auto& list = dataGenerationBuffer;
		auto size = bytesProcessed;
		dataGenerationFile->append(makeSpan(list).getFirst(size));
		list.erase(list.begin(), list.begin() + size);

		counterMutex.lock();
		currentBytesPerSecond.emplace_back
		(
			getSys()->now(),
			bytesProcessed
		);
		counterMutex.unlock();

		(void)getCurrentBytesPerSecond(TimeSpec::fromSec(60));
	}

	if (dataGenerationThreadStarted)
		return;
	if (dataGenerationFile->getReceivedLength() < 8192)
		return;

	closed = false;
	dataGenerationThreadStarted = true;
	//incRef();
	getSys()->addJob(this);
}

void NetStream::appendBytesAction(const AppendBytesAction& action)
{
	if (action == AppendBytesAction::EndSequence)
	{
		LOG
		(
			LOG_NOT_IMPLEMENTED,
			"`NetStream::appendBytesAction()`: "
			"`endSequence` isn't implemented yet."
		);
		return;
	}

	if (action == AppendBytesAction::ResetSeek)
	{
		LOG
		(
			LOG_INFO,
			"resetSeek: " << dataGenerationBuffer.size()
		);
		dataGenerationBuffer.clear();
		return;
	}

	threadAbort();
	LOG(LOG_INFO, "resetBegin");

	if (dataGenerationFile)
		delete dataGenerationFile;

	auto engineData = getSys()->getEngineData();
	dataGenerationFile = engineData->createFileStreamCache(getSys());
	dataGenerationFile->openForWriting();
	dataGenerationBuffer.clear();
	dataGenerationThreadStarted = false;
	dataGenerationExpectType = DATAGENERATION_HEADER;
}

//Tick is called from the timer thread, this happens only if a decoder is available
void NetStream::tick()
{
	//Check if the stream is paused
	if
	(
		audioStream != nullptr &&
		soundTransform.hasValue() &&
		//TODO: use soundTransform->pan
		soundTransform->volume != oldVolume
	)
	{
		audioStream->setVolume(soundTransform->volume / 100.0);
		oldVolume = soundTransform->volume;
	}

	if (paused)
		return;

	if (audioStream != nullptr && !audioStream->hasStarted)
	{
		audioStream->hasStarted = true;
		audioStream->resume();
	}

	//Advance video and audio to current time, follow the audio stream time
	counterMutex.lock();
	if (audioStream != nullptr)
	{
		assert(audioDecoder != nullptr);
		if (!streamTime)
		{
			streamTime =
			(
				audioStream->getPlayedTime() +
				audioDecoder->initialTime
			);
		}
		else if (bufferLength)
			streamTime += 1000 / frameRate;
	}
	else
	{
		if (bufferLength > 0)
			streamTime += 1000/frameRate;
		if (audioDecoder != nullptr)
			audioDecoder->skipAll();
	}

	bufferLength = std::max<ssize_t>((framesDecoded / frameRate) -
	(
		streamTime -
		prevStreamTime
	) / 1000, 0);
	//LOG(LOG_INFO,"tick:"<< " "<<bufferLength << " "<<streamTime<<" "<<frameRate<<" "<<framesdecoded<<" "<<bufferTime<<" "<<this->playbackBytesPerSecond<<" "<<this->getReceivedLength());
	countermutex.unlock();
	if (videoDecoder == nullptr)
		return;
	videoDecoder->skipUntil(streamTime);
	//The next line ensures that the downloader will not be destroyed before the upload jobs are fenced
	if (!videoDecoder->getQueued())
	{
		videoDecoder->waitForFencing();
		getSys()->getRenderThread()->addUploadJob(videoDecoder);
	}
}

void NetStream::tickFence()
{
}

bool NetStream::isReady() const
{
	//Must have videoDecoder, but audioDecoder is optional (in
	//case the video doesn't have audio)
	return
	(
		videoDecoder != nullptr &&
		videoDecoder->isValid() &&
		(audioDecoder == nullptr || audioDecoder->isValid())
	);
}

bool NetStream::lockIfReady()
{
	mutex.lock();
	bool ret = isReady();
	if (!ret) //If the data is not valid so not release the lock to keep the condition
		mutex.unlock();
	return ret;
}

void NetStream::unlock()
{
	mutex.unlock();
}

void NetStream::clearFrameBuffer()
{
	if (videoDecoder != nullptr)
		videoDecoder->clearFrameBuffer();
}

void NetStream::execute()
{
	//checkPolicyFile only applies to per-pixel access, loading and playing is always allowed.
	//So there is no need to disallow playing if policy files disallow it.
	//We do need to check if per-pixel access is allowed.
	SecurityManager::EVALUATIONRESULT evaluationResult = getSystemState()->securityManager->evaluatePoliciesURL(url, true);
	if(evaluationResult == SecurityManager::NA_CROSSDOMAIN_POLICY)
		rawAccessAllowed = true;

	std::streambuf *sbuf = nullptr;
	if (streamDecoder)
		delete streamDecoder;
	streamDecoder=nullptr;

	if (datagenerationfile)
	{
		sbuf = datagenerationfile->createReader();
	}
	else
	{
		if (!downloader)
			return;
		if(downloader->hasFailed())
		{
			this->incRef();
			getVm(getSystemState())->addEvent(_MR(this),_MR(Class<IOErrorEvent>::getInstanceS(getInstanceWorker())));
			getSystemState()->downloadManager->destroy(downloader);
			downloader = nullptr;
			return;
		}
		
		//The downloader hasn't failed yet at this point
		
		sbuf = downloader->getCache()->createReader();
	}
	istream s(sbuf);
	s.exceptions(istream::goodbit);

	ThreadProfile* profile=getSystemState()->allocateProfiler(RGB(0,0,200));
	profile->setTag("NetStream");
	bool waitForFlush=true;
	//We need to catch possible EOF and other error condition in the non reliable stream
	try
	{
#ifdef ENABLE_LIBAVCODEC
		Chronometer chronometer;
		if (!sbuf)
		{
			threadAbort();
		}
		else
		{
			countermutex.lock();
			streamDecoder=new BuiltinStreamDecoder(s,this,::ceil(bufferTime));
			if (!streamDecoder->isValid()) // not FLV stream, so we try ffmpeg detection
			{
				delete streamDecoder;
				s.seekg(0);
				streamDecoder=new FFMpegStreamDecoder(this,this->getSystemState()->getEngineData(),s,::ceil(bufferTime));
			}
			countermutex.unlock();
			if(!streamDecoder->isValid())
				threadAbort();
		}
		countermutex.lock();
		framesdecoded = 0;
		frameRate=0;
		videoDecoder = nullptr;
		this->prevstreamtime = streamTime;
		this->bufferLength = 0;
		countermutex.unlock();
		bool done=false;
		bool bufferfull = true;
		while(!done)
		{
			//Check if threadAbort has been called, if so, stop this loop
			if(closed)
			{
				done = true;
				continue;
			}
			bool decodingSuccess= bufferfull && streamDecoder->decodeNextFrame();
			if(!decodingSuccess && bufferfull)
			{
				if (s.tellg() == -1)
				{
					done = true;
					continue;
				}

				LOG(LOG_INFO,"decoding failed:"<<s.tellg()<<" "<<this->getReceivedLength());
				bufferfull = false;
			}
			else
			{
				if (streamDecoder->videoDecoder)
				{
					if (streamDecoder->videoDecoder->framesdecoded != framesdecoded)
					{
						countermutex.lock();

						framesdecoded = streamDecoder->videoDecoder->framesdecoded;
						if(frameRate==0)
						{
							assert(streamDecoder->videoDecoder->frameRate);
							frameRate=streamDecoder->videoDecoder->frameRate;
						}
						if (frameRate)
						{
							this->playbackBytesPerSecond = s.tellg() / (framesdecoded / frameRate);
							this->bufferLength = (framesdecoded / frameRate) - (streamTime-prevstreamtime)/1000.0;
						}
						countermutex.unlock();
						if (bufferfull && this->bufferLength < 0)
						{
							bufferfull = false;
							this->bufferLength=0;
							this->incRef();
							getVm(getSystemState())->addEvent(_MR(this),_MR(Class<NetStatusEvent>::getInstanceS(getInstanceWorker(),"status", "NetStream.Buffer.Empty")));
						}
					}
				}
			}
			if(videoDecoder==nullptr && streamDecoder->videoDecoder)
			{
				videoDecoder=streamDecoder->videoDecoder;
				this->incRef();
				getVm(getSystemState())->addEvent(_MR(this),
								  _MR(Class<NetStatusEvent>::getInstanceS(getInstanceWorker(),"status", "NetStream.Play.Start")));
			}
			if(audioDecoder==nullptr && streamDecoder->audioDecoder)
				audioDecoder=streamDecoder->audioDecoder;
			
			if(audioStream==nullptr && audioDecoder && audioDecoder->isValid() && getSys()->audioManager)
				audioStream=getSystemState()->audioManager->createStream(audioDecoder,streamDecoder->hasVideo(),this,-1,0,soundTransform ? number_t(soundTransform->volume)/100.0 : 1.0);
			if(!tickStarted && isReady() && frameRate && ((framesdecoded / frameRate) >= this->bufferTime))
			{
				tickStarted=true;
				paused=false;
				this->incRef();
				getVm(getSystemState())->addEvent(_MR(this),
								  _MR(Class<NetStatusEvent>::getInstanceS(getInstanceWorker(),"status", "NetStream.Buffer.Full")));
				getSystemState()->addTick(1000/frameRate,this);
				//Also ask for a render rate equal to the video one (capped at 24)
				float localRenderRate=dmin(frameRate,24);
				getSystemState()->setRenderRate(localRenderRate);
			}
			if (!bufferfull && frameRate && ((framesdecoded / frameRate) >= this->bufferTime))
			{
				bufferfull = true;
				this->incRef();
				getVm(getSystemState())->addEvent(_MR(this),
								  _MR(Class<NetStatusEvent>::getInstanceS(getInstanceWorker(),"status", "NetStream.Buffer.Full")));
			}
			profile->accountTime(chronometer.checkpoint());
			if(threadAborting)
				throw JobTerminationException();
		}
#endif //ENABLE_LIBAVCODEC
	}
	catch(LightsparkException& e)
	{
		LOG(LOG_ERROR, "Exception in NetStream " << e.cause);
		threadAbort();
		waitForFlush=false;
	}
	catch(JobTerminationException& e)
	{
		LOG(LOG_ERROR, "JobTerminationException in NetStream ");
		threadAbort();
		waitForFlush=false;
	}
	catch(exception& e)
	{
		LOG(LOG_ERROR, "Exception in reading: "<<e.what());
	}
	if(waitForFlush)
	{
		//Put the decoders in the flushing state and wait for the complete consumption of contents
		if(audioDecoder)
			audioDecoder->setFlushing();
		if(videoDecoder)
			videoDecoder->setFlushing();
		
		if(audioDecoder)
			audioDecoder->waitFlushed();
		if(videoDecoder)
			videoDecoder->waitFlushed();

		if (!this->closed)
		{
			this->incRef();
			getVm(getSystemState())->addEvent(_MR(this), _MR(Class<NetStatusEvent>::getInstanceS(getInstanceWorker(),"status", "NetStream.Buffer.Flush")));
			this->incRef();
			getVm(getSystemState())->addEvent(_MR(this), _MR(Class<NetStatusEvent>::getInstanceS(getInstanceWorker(),"status", "NetStream.Play.Stop")));
		}
	}
	//Before deleting stops ticking, removeJobs also spin waits for termination
	getSystemState()->removeJob(this);
	tickStarted=false;

	{
		Locker l(mutex);
		//Change the state to invalid to avoid locking
		videoDecoder=nullptr;
		audioDecoder=nullptr;
		//Clean up everything for a possible re-run
		if (downloader)
			getSys()->downloadManager->destroy(downloader);
		//This transition is critical, so the mutex is needed
		downloader=nullptr;
		if (audioStream)
			getSys()->audioManager->removeStream(audioStream);
		audioStream=nullptr;
	}
	if (streamDecoder)
	{
		delete streamDecoder;
		streamDecoder = nullptr;
	}
	if (sbuf)
		delete sbuf;
}

void NetStream::threadAbort()
{
	Locker l(mutex);
	//This will stop the rendering loop
	closed = true;

	if(downloader)
		downloader->stop();

	//Clear everything we have in buffers, discard all frames
	if(videoDecoder)
	{
		videoDecoder->setFlushing();
		videoDecoder->skipAll();
	}
	if(audioDecoder)
	{
		//Clear everything we have in buffers, discard all frames
		audioDecoder->setFlushing();
		audioDecoder->skipAll();
	}
}

void NetStream::sendClientNotification(const tiny_string& name, std::list<asAtom>& arglist)
{
	if (client.isNull())
		return;
	multiname callbackName(nullptr);
	callbackName.name_type=multiname::NAME_STRING;
	callbackName.name_s_id=getSys()->getUniqueStringId(name);
	callbackName.ns.push_back(nsNameAndKind(getSystemState(),"",NAMESPACE));
	asAtom callback=asAtomHandler::invalidAtom;
	client->getVariableByMultiname(callback,callbackName,GET_VARIABLE_OPTION::NONE,client->getInstanceWorker());
	if(asAtomHandler::isFunction(callback))
	{
		asAtom callbackArgs[arglist.size()];
		
		ASObject* closure = asAtomHandler::getObject(asAtomHandler::getClosureAtom(callback,asAtomHandler::invalidAtom));
		if (!closure)
			closure = client.getPtr();
		closure->incRef();
		int i= 0;
		for (auto it = arglist.cbegin();it != arglist.cend(); it++)
		{
			asAtom arg = (*it);
			ASATOM_INCREF(arg);
			callbackArgs[i++] = arg;
		}
		ASATOM_INCREF(callback);
		_R<FunctionEvent> event(new (getSys()->unaccountedMemory) FunctionEvent(callback,
				asAtomHandler::fromObject(closure), callbackArgs, arglist.size()));
		getVm(getSystemState())->addEvent(NullRef,event);
	}
}

ASFUNCTIONBODY_ATOM(NetStream,_getBytesLoaded)
{
	NetStream* th=asAtomHandler::as<NetStream>(obj);
	if(th->isReady())
		asAtomHandler::setUInt(ret,th->getReceivedLength());
	else
		asAtomHandler::setUInt(ret,0);
}

ASFUNCTIONBODY_ATOM(NetStream,_getBytesTotal)
{
	NetStream* th=asAtomHandler::as<NetStream>(obj);
	if(th->isReady())
		asAtomHandler::setUInt(ret,th->getTotalLength());
	else
		asAtomHandler::setUInt(ret,0);
}

ASFUNCTIONBODY_ATOM(NetStream,_getTime)
{
	NetStream* th=asAtomHandler::as<NetStream>(obj);
	if(th->isReady())
		asAtomHandler::setNumber(ret, th->getStreamTime()/1000.);
	else
		asAtomHandler::setUInt(ret,0);
}

ASFUNCTIONBODY_ATOM(NetStream,_getCurrentFPS)
{
	//TODO: provide real FPS (what really is displayed)
	NetStream* th=asAtomHandler::as<NetStream>(obj);
	if(th->isReady() && !th->paused)
		asAtomHandler::setNumber(ret, th->getFrameRate());
	else
		asAtomHandler::setUInt(ret,0);
}

uint32_t NetStream::getVideoWidth() const
{
	assert(isReady());
	return videoDecoder->getWidth();
}

uint32_t NetStream::getVideoHeight() const
{
	assert(isReady());
	return videoDecoder->getHeight();
}

double NetStream::getFrameRate()
{
	assert(isReady());
	return frameRate;
}

TextureChunk& NetStream::getTexture() const
{
	assert(isReady());
	return videoDecoder->getTexture();
}

uint32_t NetStream::getStreamTime()
{
	assert(isReady());
	return streamTime;
}

uint32_t NetStream::getReceivedLength()
{
	assert(isReady());
	if (datagenerationfile)
		return datagenerationfile->getReceivedLength();
	return downloader->getReceivedLength();
}

uint32_t NetStream::getTotalLength()
{
	assert(isReady());
	if (datagenerationfile)
		return 0;
	return downloader->getLength();
}
