/**************************************************************************
    Lightspark, a free flash player implementation

    Copyright (C) 2009-2013  Alessandro Pignotti (a.pignotti@sssup.it)
    Copyright (C) 2024, 2026  mr b0nk 500 (b0nk@b0nk.xyz)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
**************************************************************************/

#include "backends/audio.h"
#include "backends/builtindecoder.h"
#include "backends/net_connection.h"
#include "backends/net_stream.h"
#include "backends/rendering.h"
#include "backends/security.h"
#include "backends/streamcache.h"
#include "platforms/engineutils.h"
#include "tiny_string.h"

using namespace lightspark;

NetStream::NetStream(const NetStreamObject& _obj) :
tickStarted(false),
paused(false),
closed(true),
streamTime(0),
frameRate(0),
connection(nullptr),
downloader(nullptr),
videoDecoder(nullptr),
audioDecoder(nullptr),
audioStream(nullptr),
dataGenerationFile(nullptr),
dataGenerationThreadStarted(false),
obj(_obj),
oldVolume(-1.0),
checkPolicyFile(false),
rawAccessAllowed(false),
framesDecoded(0),
playbackBytesPerSecond(0),
maxBytesPerSecond(0),
dataGenerationExpectType(DATAGENERATION_HEADER),
streamDecoder(nullptr),
backBufferLength(0),
backBufferTime(30),
bufferLength(0),
bufferTime(0.1),
bufferTimeMax(0),
maxPauseBufferTime(0)
{
}

NetStream::~NetStream()
{
	if (tickStarted)
		getSys()->removeJob(this);
	delete videoDecoder;
	delete audioDecoder;
	if (dataGenerationFile != nullptr)
		delete dataGenerationFile;
}

size_t NetStream::getCurrentBytesPerSecond(const TimeSpec& threshold)
{
	auto now = getSys()->now();
	Locker l(counterMutex);

	auto& list = currentBytesPerSecond;
	list.erase(list.begin(), std::find_if
	(
		list.begin(),
		list.end(),
		[&](const auto& it)
		{
			return now - it.timestamp <= threshold;
		}
	));

	size_t ret = 0;
	for (const auto& it : list)
		ret += it.bytesRead;

	maxBytesPerSecond = std::min(maxBytesPerSecond, ret);
	return ret;
}

NetStreamInfo NetStream::getInfo()
{
	NetStreamInfo ret;
	if (isReady())
	{
		ret.byteCount = getReceivedLength();
		ret.dataBufferLength = getReceivedLength();
	}

	if (dataGenerationFile != nullptr)
	{
		auto curbps = getCurrentBytesPerSecond(TimeSpec::fromSec(1));
		ret.currentBytesPerSecond = curbps;
		ret.dataBytesPerSecond = curbps;
		ret.maxBytesPerSecond = maxBytesPerSecond;

		//TODO compute video/audio BytesPerSecond correctly
		ret.videoBytesPerSecond = curbps * 3 / 4;
		ret.audioBytesPerSecond = curbps / 4;
	}
	else
	{
		LOG
		(
			LOG_NOT_IMPLEMENTED,
			"`NetStreamInfo.{current,max,data}BytesPerSecond` "
			"are only implemented for data generation mode"
		);
	}

	if (videoDecoder != nullptr)
		ret.droppedFrames = videoDecoder->framesdropped;
	ret.playbackBytesPerSecond = playbackBytesPerSecond;
	ret.audioBufferLength = bufferLength;
	ret.videoBufferLength = bufferLength;
	return ret;
}

void NetStream::play(Optional<const tiny_string&> name)
{
	if (!closed)
		return;
	auto sys = getSys();
	//Make sure the stream is restarted properly
	closed = false;

	//Reset the paused states
	paused = false;
//	th->audioPaused = false;

	// `nullOpt` means the data is generated by calls to `appendBytes()`.
	if (!name.hasValue())
	{
		auto engineData = sys->getEngeineData();
		dataGenerationFile = engineData->createFileStreamCache(sys);
		dataGenerationFile->openForWriting();
		streamTime = 0;
		return;
	}

	if (th->connection.isNull())
	{
		throw RunTimeException
		(
			"`NetStream::play()`: Stream has no connection."
		);
	}

	if (connection->uri.getProtocol() == "http")
	{
		//Remoting connection used, this should not happen
		throw RunTimeException
		(
			"`NetStream::play()`: "
			"A remoting `NetConnection` was used."
		);
	}

	if (connection->uri.isValid())
	{
		//We should connect to FMS
		//Args: name, start, len, reset
		url = th->connection->uri;
		url.setStream(*name);
	}
	else
	{
		// HTTP download.
		//
		// `name` is the url.
		// TODO: What's the meaning of the other arguments?
		url = sys->mainClip->getOrigin().goToURL(*name);

		auto evalRet = sys->securityManager->evaluateURLStatic
		(
			url,
			~SecurityManager::LOCAL_WITH_FILE,
			(
				SecurityManager::LOCAL_WITH_FILE |
				SecurityManager::LOCAL_TRUSTED
			),
			//Check for navigating up in local directories (not allowed)
			true
		);

		char* error = nullptr;
		switch (evalRet)
		{
			case SecurityManager::NA_REMOTE_SANDBOX:
				error = "connect to network";
				break;
			//Local-with-filesystem sandbox can't access network
			case SecurityManager::NA_LOCAL_SANDBOX:
				error = "connect to local file";
				break;
			case SecurityManager::NA_PORT:
				error = "connect to restricted port";
				break;
			case SecurityManager::NA_RESTRICT_LOCAL_DIRECTORY:
				error = "not allowed to navigate up for local files";
				break;
			default:
				break;
		}

		if (error != nullptr)
		{
			throw RunTimeException(tiny_string
			(
				"SecurityError: `NetStream::play()`: "
			) + error);
		}
	}

	assert_and_throw(downloader == nullptr);

	//Until buffering is implemented, set a fake value. The BBC
	//news player panics if bufferLength is smaller than 2.
	//bufferLength = 10;

	if (!url.isValid())
	{
		//Notify an error during loading
		handleStatusEvent(makeSpan
		({
			{ "code", "NetStream.Play.Failed" },
			{ "level", "status" },
		}));
		handleIOError();
		return;
	}

	//The URL is valid so we can start the download and add ourself as a job
	auto cache = sys->getEngineData()->createFileStreamCache(sys);
	downloader = sys->downloadManager->download
	(
		url,
		_MR(cache),
		nullptr
	);

	streamTime = 0;
	//To be decreffed in jobFence
	//incRef();
	sys->addJob(th);
}

void NetStream::jobFence()
{
	//decRef();
}

void NetStream::resume()
{
	if (!paused)
		return;

	paused = false;
	{
		Locker l(mutex);
		if (audioStream != nullptr)
			audioStream->resume();
	}

	handleStatusEvent(makeSpan
	({
		{ "description", "Unpausing" },
		{ "level", "status" },
		{ "code", "NetStream.Unpause.Notify" },
	}));
}

void NetStream::pause()
{
	if (paused)
		return;

	paused = true;
	{
		Locker l(mutex);
		if (audioStream != nullptr)
			audioStream->pause();
	}

	handleStatusEvent(makeSpan
	({
		{ "description", "Pausing" },
		{ "level", "status" },
		{ "code", "NetStream.Pause.Notify" },
	}));
}

void NetStream::togglePause()
{
	if (paused)
		resume();
	else
		pause();
}

void NetStream::close()
{
	if (closed)
		goto end;

	//Everything is stopped in threadAbort
	threadAbort();
	prevStreamTime = 0;
	streamTime = 0;
	if (audioStream != nullptr)
		audioStream->setPlayedTime(0);
	if (audioDecoder != nullptr)
		audioDecoder->initialTime = 0;
	framesDecoded = 0;
end:
	LOG(LOG_CALLS, "NetStream::close called");
}

void NetStream::seek(ssize_t offset, bool notify)
{
	counterMutex.lock()
	if (streamDecoder != nullptr)
	{
		auto pos = offset * 1000;
		if (audioDecoder != nullptr)
			audioDecoder->skipAll();
		if (videoDecoder != nullptr)
			videoDecoder->skipAll();

		prevStreamTime = pos;
		streamTime = pos;
		if (audioStream != nullptr)
			audioStream->setPlayedTime(0);
		if (audioDecoder != nullptr)
			audioDecoder->initialTime = pos;
		streamDecoder->jumpToPosition(pos);
		framesDecoded = 0;
	}
	counterMutex.unlock();

	resume();
	if (!notify)
		return;
	std::stringstream s;
	s << "Start Seeking " << size_t(offset);

	handleStatusEvent(makeSpan
	({
		{ "description", s.str() },
		{ "level", "status" },
		{ "code", "NetStream.SeekStart.Notify" },
	}));
}

void NetStream::appendBytes(Span<uint8_t> data)
{
	if (data.empty() || dataGenerationFile == nullptr)
		return;

	//th->datagenerationfile->append(bytearray->getBuffer(bytearray->getLength(),false),bytearray->getLength());
	dataGenerationBuffer.insert
	(
		dataGenerationBuffer.end(),
		data.begin(),
		data.end()
	);

	size_t bytesProcessed = 0;
	auto span = makeSpan(dataGenerationBuffer);
	for (bool done = false; !done;)
	{
		switch (dataGenerationExpectType)
		{
			case DATAGENERATION_HEADER:
			{
				// TODO check for correct header?
				// skip flv header
				span = span.subSpan(5);
				if (span.getSize() < 4)
				{
					done = true;
					break;
				}
				// header length is always in big endian
				auto headerSize = span.atBE<uint32_t>(0);
				if (!headerSize)
				{
					done = true;
					break;
				}

				span = span.subSpan(headerSize);
				dataGenerationExpectType = DATAGENERATION_PREVTAG;
				bytesProcessed += headerSize;
				break;
			}
			case DATAGENERATION_PREVTAG:
			{
				// prevtag (value may be wrong as we don't check for big endian)
				if (span.getSize() < 4)
				{
					done = true;
					break;
				}
				span = span.subSpan(4);
				dataGenerationExpectType = DATAGENERATION_FLVTAG;
				break;
			}
			case DATAGENERATION_FLVTAG:
			{
				if (span.getSize() < 4)
				{
					done = true;
					break;
				}

				auto tagType = span[0];
				auto dataSize = span.atBE<uint32_t>(0) & 0xffffff;
				dataSize += 1 + 3 + 3 + 1 + 3;
				if (dataSize + bytesProcessed >= dataGenerationBuffer.size())
					break;
				bytesProcessed += dataSize;
				span = span.subSpan(dataSize)
				th->dataGenerationExpectType = DATAGENERATION_PREVTAG;
				break;
			}
			default:
				LOG
				(
					LOG_ERROR,
					"invalid DATAGENERATION_EXPECT_TYPE: " <<
					dataGenerationExpectType
				);
				done = true;
				break;
		}
	}

	if (bytesProcessed)
	{
		auto& list = dataGenerationBuffer;
		auto size = bytesProcessed;
		dataGenerationFile->append(makeSpan(list).getFirst(size));
		list.erase(list.begin(), list.begin() + size);

		counterMutex.lock();
		currentBytesPerSecond.emplace_back
		(
			getSys()->now(),
			bytesProcessed
		);
		counterMutex.unlock();

		(void)getCurrentBytesPerSecond(TimeSpec::fromSec(60));
	}

	if (dataGenerationThreadStarted)
		return;
	if (dataGenerationFile->getReceivedLength() < 8192)
		return;

	closed = false;
	dataGenerationThreadStarted = true;
	//incRef();
	getSys()->addJob(this);
}

void NetStream::appendBytesAction(const AppendBytesAction& action)
{
	if (action == AppendBytesAction::EndSequence)
	{
		LOG
		(
			LOG_NOT_IMPLEMENTED,
			"`NetStream::appendBytesAction()`: "
			"`endSequence` isn't implemented yet."
		);
		return;
	}

	if (action == AppendBytesAction::ResetSeek)
	{
		LOG
		(
			LOG_INFO,
			"resetSeek: " << dataGenerationBuffer.size()
		);
		dataGenerationBuffer.clear();
		return;
	}

	threadAbort();
	LOG(LOG_INFO, "resetBegin");

	if (dataGenerationFile)
		delete dataGenerationFile;

	auto engineData = getSys()->getEngineData();
	dataGenerationFile = engineData->createFileStreamCache(getSys());
	dataGenerationFile->openForWriting();
	dataGenerationBuffer.clear();
	dataGenerationThreadStarted = false;
	dataGenerationExpectType = DATAGENERATION_HEADER;
}

//Tick is called from the timer thread, this happens only if a decoder is available
void NetStream::tick()
{
	//Check if the stream is paused
	if
	(
		audioStream != nullptr &&
		soundTransform.hasValue() &&
		//TODO: use soundTransform->pan
		soundTransform->volume != oldVolume
	)
	{
		audioStream->setVolume(soundTransform->volume / 100.0);
		oldVolume = soundTransform->volume;
	}

	if (paused)
		return;

	if (audioStream != nullptr && !audioStream->hasStarted)
	{
		audioStream->hasStarted = true;
		audioStream->resume();
	}

	//Advance video and audio to current time, follow the audio stream time
	counterMutex.lock();
	if (audioStream != nullptr)
	{
		assert(audioDecoder != nullptr);
		if (!streamTime)
		{
			streamTime =
			(
				audioStream->getPlayedTime() +
				audioDecoder->initialTime
			);
		}
		else if (bufferLength)
			streamTime += 1000 / frameRate;
	}
	else
	{
		if (bufferLength > 0)
			streamTime += 1000/frameRate;
		if (audioDecoder != nullptr)
			audioDecoder->skipAll();
	}

	bufferLength = std::max<ssize_t>((framesDecoded / frameRate) -
	(
		streamTime -
		prevStreamTime
	) / 1000, 0);
	//LOG(LOG_INFO,"tick:"<< " "<<bufferLength << " "<<streamTime<<" "<<frameRate<<" "<<framesdecoded<<" "<<bufferTime<<" "<<this->playbackBytesPerSecond<<" "<<this->getReceivedLength());
	counterMutex.unlock();
	if (videoDecoder == nullptr)
		return;
	videoDecoder->skipUntil(streamTime);
	//The next line ensures that the downloader will not be destroyed before the upload jobs are fenced
	if (!videoDecoder->getQueued())
	{
		videoDecoder->waitForFencing();
		getSys()->getRenderThread()->addUploadJob(videoDecoder);
	}
}

void NetStream::tickFence()
{
}

bool NetStream::isReady() const
{
	//Must have videoDecoder, but audioDecoder is optional (in
	//case the video doesn't have audio)
	return
	(
		videoDecoder != nullptr &&
		videoDecoder->isValid() &&
		(audioDecoder == nullptr || audioDecoder->isValid())
	);
}

bool NetStream::lockIfReady()
{
	mutex.lock();
	bool ret = isReady();
	if (!ret) //If the data is not valid so not release the lock to keep the condition
		mutex.unlock();
	return ret;
}

void NetStream::unlock()
{
	mutex.unlock();
}

void NetStream::clearFrameBuffer()
{
	if (videoDecoder != nullptr)
		videoDecoder->clearFrameBuffer();
}

void NetStream::execute()
{
	auto sys = getSys();
	//checkPolicyFile only applies to per-pixel access, loading and playing is always allowed.
	//So there is no need to disallow playing if policy files disallow it.
	//We do need to check if per-pixel access is allowed.
	auto evalRet = sys->securityManager->evaluatePoliciesURL
	(
		url,
		true
	);

	if (evalRet == SecurityManager::NA_CROSSDOMAIN_POLICY)
		rawAccessAllowed = true;

	std::streambuf* sbuf = nullptr;
	if (streamDecoder != nullptr)
		delete streamDecoder;
	streamDecoder = nullptr;

	if (dataGenerationFile != nullptr)
		sbuf = dataGenerationFile->createReader();
	else if (downloader == nullptr)
		return;
	else if (downloader->hasFailed())
	{
		handleStatusEvent(makeSpan
		({
			{ "description", "Downloader failed" },
			{ "code", "NetStream.Play.Failed" },
			{ "level", "error" }
		}));
		handleIOError();
		sys->downloadManager->destroy(downloader);
		downloader = nullptr;
		return;
	}
	else
	{
		//The downloader hasn't failed yet at this point
		sbuf = downloader->getCache()->createReader();
	}

	std::istream s(sbuf);
	s.exceptions(istream::goodbit);

	auto profile = sys->allocateProfiler(RGB(0, 0, 200));
	profile->setTag("NetStream");
	bool waitForFlush = true;
	//We need to catch possible EOF and other error condition in the non reliable stream
	try
	{
#ifdef ENABLE_LIBAVCODEC
		Chronometer chronometer;
		if (sbuf == nullptr)
			threadAbort();
		else
		{
			counterMutex.lock();
			streamDecoder = new BuiltinStreamDecoder
			(
				s,
				this,
				std::ceil(bufferTime)
			);
			if (!streamDecoder->isValid()) // not FLV stream, so we try ffmpeg detection
			{
				delete streamDecoder;
				s.seekg(0);
				streamDecoder = new FFMpegStreamDecoder
				(
					this,
					sys->getEngineData(),
					s,
					std::ceil(bufferTime)
				);
			}
			counterMutex.unlock();
			if(!streamDecoder->isValid())
				threadAbort();
		}

		counterMutex.lock();
		framesDecoded = 0;
		frameRate = 0;
		videoDecoder = nullptr;
		prevStreamTime = streamTime;
		bufferLength = 0;
		counterMutex.unlock();

		bool bufferFull = true;
		for (;;)
		{
			//Check if threadAbort has been called, if so, stop this loop
			if (closed)
				break;
			bool decodingSuccess = bufferFull && streamDecoder->decodeNextFrame();
			if (!decodingSuccess && bufferFull)
			{
				if (s.tellg() == -1)
					break;
				LOG
				(
					LOG_INFO,
					"decoding failed: " <<
					s.tellg() << ' ' <<
					getReceivedLength()
				);
				bufferFull = false;
			}
			else if
			(
				streamDecoder->videoDecoder != nullptr &&
				streamDecoder->videoDecoder->framesdecoded != framesDecoded
			)
			{
				counterMutex.lock();

				framesDecoded = streamDecoder->videoDecoder->framesDecoded;
				if (!frameRate)
				{
					assert(streamDecoder->videoDecoder->frameRate);
					frameRate = streamDecoder->videoDecoder->frameRate;
				}

				if (frameRate)
				{
					playbackBytesPerSecond = s.tellg() /
					(
						framesDecoded /
						frameRate
					);
					bufferLength =
					(
						framesDecoded /
						frameRate
					) -
					(
						streamTime -
						prevStreamTime
					) / 1000;
				}
				counterMutex.unlock();

				if (bufferFull && bufferLength < 0)
				{
					bufferFull = false;
					bufferLength = 0;
					handleStatusEvent(makeSpan
					({
						{ "code", "NetStream.Buffer.Empty" },
						{ "level", "status" }
					}));
				}
			}

			if
			(
				videoDecoder == nullptr &&
				streamDecoder->videoDecoder != nullptr
			)
			{
				videoDecoder = streamDecoder->videoDecoder;
				handleStatusEvent(makeSpan
				({
					{ "code", "NetStream.Play.Start" },
					{ "level", "status" }
				}));
			}

			if
			(
				audioDecoder == nullptr &&
				streamDecoder->audioDecoder != nullptr
			)
				audioDecoder = streamDecoder->audioDecoder;

			if
			(
				audioStream == nullptr &&
				audioDecoder != nullptr &&
				audioDecoder->isValid() &&
				sys->audioManager != nullptr
			)
			{
				audioStream = sys->audioManager->createStream
				(
					audioDecoder,
					streamDecoder->hasVideo(),
					this,
					-1,
					0,
					soundTransform.hasValue() ?
					soundTransform->volume / 100.0 :
					1.0
				);
			}

			if
			(
				!tickStarted &&
				isReady() &&
				frameRate &&
				(framesDecoded / frameRate) >= bufferTime
			)
			{
				tickStarted = true;
				paused = false;
				handleStatusEvent(makeSpan
				({
					{ "code", "NetStream.Buffer.Full" },
					{ "level", "status" }
				}));

				//Also ask for a render rate equal to the video one (capped at 24)
				sys->setRenderRate(dmin(frameRate, 24));
			}

			if
			(
				!bufferFull &&
				frameRate &&
				(framesDecoded / frameRate) >= bufferTime
			)
			{
				bufferFull = true;
				handleStatusEvent(makeSpan
				({
					{ "code", "NetStream.Buffer.Full" },
					{ "level", "status" }
				}));
			}
			profile->accountTime(chronometer.checkpoint());
			if (threadAborting)
				throw JobTerminationException();
		}
#endif //ENABLE_LIBAVCODEC
	}
	catch (LightsparkException& e)
	{
		LOG(LOG_ERROR, "Exception in NetStream " << e.cause);
		threadAbort();
		waitForFlush = false;
	}
	catch (JobTerminationException& e)
	{
		LOG(LOG_ERROR, "JobTerminationException in NetStream ");
		threadAbort();
		waitForFlush = false;
	}
	catch (std::exception& e)
	{
		LOG(LOG_ERROR, "Exception in reading: " << e.what());
	}

	if (waitForFlush)
	{
		//Put the decoders in the flushing state and wait for the complete consumption of contents
		if (audioDecoder != nullptr)
			audioDecoder->setFlushing();
		if (videoDecoder != nullptr)
			videoDecoder->setFlushing();
		
		if (audioDecoder != nullptr)
			audioDecoder->waitFlushed();
		if (videoDecoder != nullptr)
			videoDecoder->waitFlushed();

		if (!closed)
		{
			handleStatusEvent(makeSpan
			({
				{ "code", "NetStream.Buffer.Flush" },
				{ "level", "status" }
			}));

			handleStatusEvent(makeSpan
			({
				{ "code", "NetStream.Play.Stop" },
				{ "level", "status" }
			}));
		}
	}

	//Before deleting stops ticking, removeJobs also spin waits for termination
	sys->removeJob(this);
	tickStarted = false;

	{
		Locker l(mutex);
		//Change the state to invalid to avoid locking
		videoDecoder = nullptr;
		audioDecoder = nullptr;
		//Clean up everything for a possible re-run
		if (downloader != nullptr)
			sys->downloadManager->destroy(downloader);
		//This transition is critical, so the mutex is needed
		downloader = nullptr;
		if (audioStream != nullptr)
			sys->audioManager->removeStream(audioStream);
		audioStream = nullptr;
	}

	if (streamDecoder != nullptr)
	{
		delete streamDecoder;
		streamDecoder = nullptr;
	}

	if (sbuf != nullptr)
		delete sbuf;
}

void NetStream::threadAbort()
{
	Locker l(mutex);
	//This will stop the rendering loop
	closed = true;

	if (downloader != nullptr)
		downloader->stop();

	//Clear everything we have in buffers, discard all frames
	if (videoDecoder != nullptr)
	{
		videoDecoder->setFlushing();
		videoDecoder->skipAll();
	}
	if (audioDecoder != nullptr)
	{
		//Clear everything we have in buffers, discard all frames
		audioDecoder->setFlushing();
		audioDecoder->skipAll();
	}
}

void NetStream::sendClientNotification
(
	const tiny_string& name,
	const AVM0Value& val
)
{
	switch (obj.getType())
	{
		case NetStreamObject::Type::AVM1:
			sendAVM1ClientNotification(name, val.toAVM1Value());
			break;
		case NetStreamObject::Type::AVM2:
			sendAVM2ClientNotification(name, val.toASAtom());
			break;
		default:
			break;
	}
}

void NetStream::sendAVM1ClientNotification
(
	const tiny_string& name,
	const AVM1Value& val
)
{
	auto _obj = getAVM1Obj();
	assert(!_obj.isNull());

	AVM1Activation act
	(
		getSys(),
		"[FLV " + name + ']',
		getSys()->stage->mainClip
	);

	try
	{
		(void)val.callMethod
		(
			act,
			name,
			{ val },
			AVM1ExecutionReason::Special
		);
	}
	catch (std::exception& e)
	{
		LOG
		(
			LOG_ERROR,
			"Got error while handling an AVM1 `" << name << "` "
			"handler from a `NetStream`. "
			"Reason: " << e.what()
		);
	}
}

void NetStream::sendAVM2ClientNotification
(
	const tiny_string& name,
	const asAtom& val
)
{
	auto _obj = getASObj();
	assert(!_obj.isNull());

	if (client.isNull())
		return;

	auto sys = getSys();
	multiname callbackName(nullptr);
	callbackName.name_type = multiname::NAME_STRING;
	callbackName.name_s_id = sys->getUniqueStringId(name);
	callbackName.ns.emplace_back(sys, "", NAMESPACE);
	auto callback = asAtomHandler::invalidAtom;
	client->getVariableByMultiname
	(
		callback,
		callbackName,
		GET_VARIABLE_OPTION::NONE,
		client->getInstanceWorker()
	);

	if (!asAtomHandler::isFunction(callback))
		return;

	auto closure = asAtomHandler::getObject(asAtomHandler::getClosureAtom
	(
		callback,
		asAtomHandler::invalidAtom
	));

	if (closure == nullptr)
		closure = client.getPtr();
	closure->incRef();

	ASATOM_INCREF(val);
	ASATOM_INCREF(callback);
	auto event = _MR(new (sys->unaccountedMemory) FunctionEvent
	(
		callback,
		asAtomHandler::fromObject(closure),
		&val,
		1
	));
	getVm(sys)->addEvent(NullRef, event);
}

void NetStream::handleStatusEvent(Span<const KVPair> values)
{
	switch (obj.getType())
	{
		case NetStreamObject::Type::AVM1:
			handleAVM1StatusEvent(values);
			break;
		case NetStreamObject::Type::AVM2:
			handleAVM2StatusEvent(values);
			break;
		default:
			break;
	}
}

void NetStream::handleAVM1StatusEvent(Span<const KVPair> values)
{
	auto _obj = getAVM1Obj();
	assert(!_obj.isNull());

	AVM1Activation act
	(
		getSys(),
		"[NetStream Status Event]"
		getSys()->stage->mainClip
	);

	auto infoObj = NEW_GC_PTR(act.getGcCtx(), AVM1Object
	(
		act.getGcCtx(),
		act.getPrototypes()->object->proto
	));

	for (const auto& pair : values)
		infoObj->setProp(act, pair.first, pair.second);

	try
	{
		(void)val.callMethod
		
		(
			act,
			"onStatus",
			{ infoObj },
			AVM1ExecutionReason::Special
		);
	}
	catch (std::exception& e)
	{
		LOG
		(
			LOG_ERROR,
			"Got error while handling an AVM1 `onStatus` "
			"handler from a `NetStream`. "
			"Reason: " << e.what()
		);
	}
}

void NetStream::handleAVM2StatusEvent(Span<const KVPair> values)
{
	auto tryGetVal = [&](const tiny_string& name)
	{
		auto it = std::find_if
		(
			values.begin(),
			values.end(),
			[&](const auto& pair)
			{
				return pair.first == name;
			}
		);
		return it != values.end() ? it->second : "";
	};

	auto _obj = getASObj();
	assert(!_obj.isNull());

	_obj->incRef();
	getVm(getSys())->addEvent
	(
		_MR(_obj),
		_MR(Class<NetStatusEvent>::getInstanceS
		(
			_obj->getInstanceWorker(),
			tryGetVal("level"),
			tryGetVal("status")
		))
	);
}

void NetStream::handleIOError()
{
	auto _obj = obj.getASObj();
	if (_obj.isNull())
		return;

	_obj->incRef();
	getVm(getSys())->addEvent
	(
		_MR(_obj),
		_MR(Class<IOErrorEvent>::getInstanceS(_obj->getInstanceWorker()))
	);
}

size_t NetStream::getBytesLoaded() const
{
	return isReady() ? getReceivedLength() : 0;
}

size_t NetStream::getBytesTotal() const
{
	return isReady() ? getTotalLength() : 0;
}

number_t NetStream::getTime() const
{
	return isReady() ? getStreamTime() / 1000.0 : 0;
}

number_t NetStream::getCurrentFPS() const
{
	//TODO: provide real FPS (what really is displayed)
	return isReady() && !paused ? getFrameRate() : 0;
}

const Vector2u& NetStream::getVideoSize() const
{
	assert(isReady());
	return videoDecoder->getSize();
}

number_t NetStream::getFrameRate()
{
	assert(isReady());
	return frameRate;
}

TextureChunk& NetStream::getTexture() const
{
	assert(isReady());
	return videoDecoder->getTexture();
}

size_t NetStream::getStreamTime()
{
	assert(isReady());
	return streamTime;
}

size_t NetStream::getReceivedLength()
{
	assert(isReady());
	return
	(
		dataGenerationFile != nullptr ?
		dataGenerationFile->getReceivedLength() :
		downloader->getReceivedLength()
	);
}

size_t NetStream::getTotalLength()
{
	assert(isReady());
	return dataGenerationFile != nullptr ? 0 : downloader->getLength();
}
