/**************************************************************************
    Lightspark, a free flash player implementation

    Copyright (C) 2024  mr b0nk 500 (b0nk@b0nk.xyz)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
**************************************************************************/

/* This file was generated by forward-declare-gen.sh. - DO NOT EDIT */

#ifndef FORWARDS_SCRIPTING_ABCTYPES_H
#define FORWARDS_SCRIPTING_ABCTYPES_H 1

namespace lightspark
{

/* forward declarations */
class u8;
class u16;
class s24;
class u30;
class s32;
class d64;
class string_info;
struct namespace_info;
struct ns_set_info;
struct multiname_info;
struct cpool_info;
struct option_detail;
struct item_info;
struct metadata_info;
struct traits_info;
struct instance_info;
struct class_info;
struct script_info;
struct exception_info_abc;
struct method_info_simple;
struct preloadedcodedata;
struct localconstantslot;
struct method_body_info;

};
#endif /* FORWARDS_SCRIPTING_ABCTYPES_H */
