/**************************************************************************
    Lightspark, a free flash player implementation

    Copyright (C) 2024  mr b0nk 500 (b0nk@b0nk.xyz)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
**************************************************************************/

/* This file was generated by forward-declare-gen.sh. - DO NOT EDIT */

#ifndef FORWARDS_SCRIPTING_FLASH_DISPLAY3D_FLASHDISPLAY3D_H
#define FORWARDS_SCRIPTING_FLASH_DISPLAY3D_FLASHDISPLAY3D_H 1

namespace lightspark
{

/* forward declarations */
struct SamplerRegister;
struct RegisterMapEntry;
struct renderaction;
struct constantregister;
struct attribregister;
class Context3D;
class Context3DBlendFactor;
class Context3DBufferUsage;
class Context3DClearMask;
class Context3DCompareMode;
class Context3DMipFilter;
class Context3DProfile;
class Context3DProgramType;
class Context3DRenderMode;
class Context3DStencilAction;
class Context3DTextureFilter;
class Context3DTextureFormat;
class Context3DTriangleFace;
class Context3DVertexBufferFormat;
class Context3DWrapMode;
class IndexBuffer3D;
class Program3D;
class VertexBuffer3D;

};
#endif /* FORWARDS_SCRIPTING_FLASH_DISPLAY3D_FLASHDISPLAY3D_H */
