on:
  create:
    tags:
      - '[0-9]+'

name: Draft Release

jobs:
  draft_release:
    name: Create Release
    runs-on: ubuntu-latest
    continue-on-error: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag_name: ${{ steps.tag_name.outputs.tag_name }}
      version: ${{ steps.changelog.outputs.version }}
    steps:
      - uses: actions/checkout@v6

      - name: Generate body from ChangeLog
        id: changelog
        run: |
          export VERSION=`echo "${{ github.ref }}" \
              | sed -e "s/refs\/tags\///"`
          ./.github/parse_changelog.py $VERSION ChangeLog >release.txt
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.version }}
          release_name: ${{ steps.changelog.outputs.version }}
          bodyFile: release.txt
          draft: true
          prerelease: false

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    needs: draft_release
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - uses: actions/checkout@v6
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: lightspark-v${{ needs.draft_release.outputs.version }}.flatpak
          manifest-path: flatpak/org.lightspark.lightspark.yaml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Upload Flatpak Release Asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.draft_release.outputs.version }}
          draft: true
          files: lightspark-v${{ needs.draft_release.outputs.version }}.flatpak

  msys2_64:
    name: Windows 64-bit (msys2 Build)
    runs-on: windows-latest
    continue-on-error: false
    needs: draft_release
    env:
      CFLAGS: -std=c11
      CXXFLAGS: -std=c++14
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-make
            mingw-w64-x86_64-fontconfig
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-rtmpdump
            mingw-w64-x86_64-ffmpeg
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-nsis
            upx
            git
            base-devel
      - uses: actions/checkout@v6

      - name: Run msys2 Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release .
          cmake --build .
          sed -i -e "s/Lightspark Team/The Lightspark Developers/g" CPackConfig.cmake
          cmake --install . --strip
          cmake --build . --target package
          mv -v Lightspark*exe Lightspark-v${{ needs.draft_release.outputs.version }}-Installer-win64.exe

      - name: Upload Installer Release Asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.draft_release.outputs.version }}
          draft: true
          files: Lightspark-v${{ needs.draft_release.outputs.version }}-Installer-win64.exe
